import jsPDF from "jspdf";

type AssessmentData = {
  date: string;
  patientName: string;
  age: number;
  sex: string;
  contactNumber: string;
  occupation?: string | null;
  place: string;
  outletName: string;
  height: number;
  weight: number;
  bmi: number;
  selectedTests: string[];
  variationResults?: string | null;
  dietPlanNotes?: string | null;
  remarks?: string | null;
  needsDietPlan: string;
  resultReceivedAt: string;
  interactionAt: string;
};

export function generatePatientPDF(data: AssessmentData): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 30, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("NAMS", 14, 14);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Nutrition Assessment Management System", 14, 22);
  doc.text("Sahakar Smart Clinic", pageWidth - 14, 14, { align: "right" });
  doc.text(`Report Date: ${new Date().toLocaleDateString("en-GB")}`, pageWidth - 14, 22, {
    align: "right",
  });

  let y = 40;

  // Section helper
  const section = (title: string, content: Record<string, string | number>) => {
    // Section header
    doc.setFillColor(241, 245, 249);
    doc.rect(14, y - 5, pageWidth - 28, 8, "F");
    doc.setTextColor(13, 148, 136);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, 18, y);
    y += 10;

    // Content
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    for (const [key, value] of Object.entries(content)) {
      doc.setFont("helvetica", "bold");
      doc.text(`${key}:`, 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(String(value || "—"), 65, y);
      y += 6;
    }
    y += 4;
  };

  // Patient Info
  section("Patient Information", {
    Name: data.patientName,
    Age: data.age,
    Sex: data.sex,
    Contact: data.contactNumber,
    Occupation: data.occupation || "—",
    Place: data.place,
    Outlet: data.outletName,
  });

  // Biometrics
  const bmiCategory =
    data.bmi < 18.5
      ? "Underweight"
      : data.bmi < 25
        ? "Normal"
        : data.bmi < 30
          ? "Overweight"
          : "Obese";

  section("Biometrics", {
    Height: data.height ? `${data.height} cm` : "N/A",
    Weight: data.weight ? `${data.weight} kg` : "N/A",
    BMI: data.bmi ? `${data.bmi} (${bmiCategory})` : "N/A",
  });

  // Lab Tests
  section("Tests Conducted", {
    Tests: data.selectedTests.join(", ") || "None",
  });

  // Clinical Notes
  section("Clinical Notes", {
    "Variation in Results": data.variationResults || "—",
    "Diet Plan Advice": data.dietPlanNotes || "—",
    "Needs Diet Plan": data.needsDietPlan,
    Remarks: data.remarks || "—",
  });

  // Timestamps
  section("Consultation Details", {
    "Result Received": data.resultReceivedAt,
    "Patient Interaction": data.interactionAt,
  });

  // Footer
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y + 5, pageWidth - 14, y + 5);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Generated by NAMS — Nutrition Assessment Management System",
    pageWidth / 2,
    y + 12,
    { align: "center" }
  );

  return doc;
}
